# 共通設定
common:
  encoding: cp932
  date_format: "%Y%m"

# 給与データ処理ルール
salary:
  # 入力データの検証設定（元のカラム名を使用）
  input:
    # 必須列の定義
    required_columns:
      - 会社NO
      - 対象年月
      - コード
      - 氏名
      - 所属コード1
      - 所属コード1名
      - 事業所
      - 事業所名
      - 所属
      - 所属名
      - 部門
      - 部門名
      - 資格
      - 原価区分
      - 基本給
      - 残業平日普通
      - 残業平日深夜
      - 60超手当
      - 休日勤務手当
      - 休日深夜手当
      - 遅刻早退控除
      - 割増手当
      - 割増深夜手当
      - 欠勤控除
      - 固･職級手当
      - 固･役職手当
      - 固･家族手当
      - 住宅手当
      - 食事手当
      - 固･調整手当
      - 固･その他
      - 特別勤務手当
      - 在宅勤務手当
      - 変動その他
      - 固･DC代替措置
      - DC掛金初月
      - 呼出勤務手当
      - 褒賞金
      - 公的資格合格金
      - 遡及分
      - 課税通勤
      - 非課税通勤
      - 課税合計
      - 総支給額合計
      - P健保介護
      - 厚生年金個人
      - 雇用保険
      - 所得税
      - 住民税
      - 年調過不足
      - 加入者拠出
      - ランチ弁当代
      - ﾜｰｸﾘｨ知多
      - 自動車保険
      - ＣＭ会費
      - ＴＧ特別医療
      - 健保給付金等
      - 会社立替精算
      - その他控除
      - 差引支給額
      - 差引支給＿負
      - 振込金額1

      

    # 数値列の定義（元のカラム名を使用）
    numeric_columns:
      # 基本給与
      - 基本給
      # 資格手当
      - 固･職級手当
      - 固･役職手当
      - 資格手当合計
      # 時間外手当
      - 残業平日普通
      - 残業平日深夜
      - 60超手当
      - 休日勤務手当
      - 休日深夜手当
      - 遅刻早退控除
      - 割増手当
      - 割増深夜手当
      - 欠勤控除
      - 時間外勤務手当合計
      # その他手当
      - 固･家族手当
      - 住宅手当
      - 食事手当
      - 固･調整手当
      - 固･その他
      - 特別勤務手当
      - 在宅勤務手当
      - 呼出勤務手当
      - 褒賞金
      - 公的資格合格金
      - 遡及分
      - 変動その他
      - 固･DC代替措置
      - DC掛金初月
      - その他手当合計
      # 通勤手当
      - 課税通勤
      - 非課税通勤
      - 通勤手当合計
      # 控除項目
      - P健保介護
      - 厚生年金個人
      - 雇用保険
      - 所得税
      - 住民税
      - 年調過不足
      - 加入者拠出
      - ランチ弁当代
      - ﾜｰｸﾘｨ知多
      - 自動車保険
      - ＣＭ会費
      - ＴＧ特別医療
      - 会社立替精算
      - その他控除
      - 健保給付金等
      - 控除合計
      # 最終計算項目
      - 支給総額
      - 総支給額合計
      - 差引支給額
      - 差引支給＿負
      - 振込金額1
  

  # 入力データのグループ定義（元のカラム名を使用）
  input_columns:
    # 基本情報カラム
    basic_info:
      - 会社NO
      - 対象年月
      - コード
      - 氏名
      - 原価区分
      - 所属
      - 所属名
      - 所属コード1
      - 所属コード1名
      - 事業所
      - 事業所名
      - 部門
      - 部門名

    # 給与カラム
    groups:
      # 基本給与
      base:
        - 基本給
      # 資格手当
      qualification:
        - 固･職級手当
        - 固･役職手当
      # 時間外手当
      overtime:
        - 残業平日普通
        - 残業平日深夜
        - 60超手当
        - 休日勤務手当
        - 休日深夜手当
        - 遅刻早退控除
        - 割増手当
        - 割増深夜手当
        - 欠勤控除
      # その他手当
      allowance:
        - 固･家族手当
        - 住宅手当
        - 食事手当
        - 固･調整手当
        - 固･その他
        - 特別勤務手当
        - 在宅勤務手当
        - 呼出勤務手当
        - 褒賞金
        - 公的資格合格金
        - 遡及分
        - 変動その他
        - 固･DC代替措置
        - DC掛金初月
      # 通勤手当
      commute:
        - 課税通勤
        - 非課税通勤
      # 控除項目
      deduction:
        - P健保介護
        - 厚生年金個人
        - 雇用保険
        - 所得税
        - 住民税
        - 年調過不足
        - 加入者拠出
        - ランチ弁当代
        - ﾜｰｸﾘｨ知多
        - 自動車保険
        - ＣＭ会費
        - ＴＧ特別医療
        - 会社立替精算
        - その他控除
        - 健保給付金等
      # 支給総額
      total_payment:
        - 基本給
        - 資格手当合計
        - 時間外勤務手当合計
        - その他手当合計
        - 通勤手当合計
      transfer_payment:
        - 支給総額
        - 健保給付金等
        - 差引支給＿負

  # 出力設定（※変換後のカラム名を使用）
  output_settings:
    summary:
      required_columns:
        - 対象年月
        - コード
        - 氏名
        - 原価区分
        - 雇用区分コード
        - 雇用区分
        - 部門コード
        - 部門
        - 部署コード
        - 部署
        - セグメントコード
        - セグメント
        - 基本給
        - 資格手当合計
        - 時間外勤務手当合計
        - その他手当合計
        - 通勤手当合計
        - 支給総額
        - 控除合計
        - 差引支給額
        - 振込金額

      columns_order:
        - 対象年月
        - コード
        - 氏名
        - 原価区分
        - 雇用区分コード
        - 雇用区分
        - 部門コード
        - 部門
        - 部署コード
        - 部署
        - セグメントコード
        - セグメント
        - 基本給
        - 資格手当合計
        - 時間外勤務手当合計
        - その他手当合計
        - 通勤手当合計
        - 支給総額
        - 控除合計
        - 差引支給額
        - 振込金額
      
    detail:
      required_columns:
        - 対象年月
        - コード
        - 氏名
        - 原価区分
        - 雇用区分コード
        - 雇用区分
        - 部門コード
        - 部門
        - 部署コード
        - 部署
        - セグメントコード
        - セグメント
        - 基本給
        - 固･職級手当
        - 固･役職手当
        - 資格手当合計
        - 残業平日普通
        - 残業平日深夜
        - 60超手当
        - 休日勤務手当
        - 休日深夜手当
        - 割増手当
        - 割増深夜手当
        - 遅刻早退控除
        - 欠勤控除
        - 時間外勤務手当合計
        - 固･家族手当
        - 住宅手当
        - 食事手当
        - 固･調整手当
        - 固･その他
        - 特別勤務手当
        - 在宅勤務手当
        - 呼出勤務手当
        - 褒賞金
        - 公的資格合格金
        - 遡及分
        - 変動その他
        - 固･DC代替措置
        - DC掛金初月
        - その他手当合計
        - 課税通勤
        - 非課税通勤
        - 通勤手当合計
        - 支給総額
        - P健保介護
        - 厚生年金個人
        - 雇用保険
        - 所得税
        - 住民税
        - 年調過不足
        - 加入者拠出
        - ランチ弁当代
        - ﾜｰｸﾘｨ知多
        - 自動車保険
        - ＣＭ会費
        - ＴＧ特別医療
        - 会社立替精算
        - その他控除
        - 健保給付金等
        - 控除合計
        - 差引支給額
        - 差引支給＿負
        - 振込金額
        
      columns_order:
        - 対象年月
        - コード
        - 氏名
        - 原価区分
        - 雇用区分コード
        - 雇用区分
        - 部門コード
        - 部門
        - 部署コード
        - 部署
        - セグメントコード
        - セグメント
        - 基本給
        - 固･職級手当
        - 固･役職手当
        - 資格手当合計
        - 残業平日普通
        - 残業平日深夜
        - 60超手当
        - 休日勤務手当
        - 休日深夜手当
        - 遅刻早退控除
        - 割増手当
        - 割増深夜手当
        - 欠勤控除
        - 時間外勤務手当合計
        - 固･家族手当
        - 住宅手当
        - 食事手当
        - 固･調整手当
        - 固･その他
        - 特別勤務手当
        - 在宅勤務手当
        - 呼出勤務手当
        - 褒賞金
        - 公的資格合格金
        - 遡及分
        - 変動その他
        - 固･DC代替措置
        - DC掛金初月
        - その他手当合計
        - 課税通勤
        - 非課税通勤
        - 通勤手当合計
        - 支給総額
        - P健保介護
        - 厚生年金個人
        - 雇用保険
        - 所得税
        - 住民税
        - 年調過不足
        - 加入者拠出
        - ランチ弁当代
        - ﾜｰｸﾘｨ知多
        - 自動車保険
        - ＣＭ会費
        - ＴＧ特別医療
        - 会社立替精算
        - その他控除
        - 健保給付金等
        - 控除合計
        - 差引支給額
        - 差引支給＿負
        - 振込金額
        

  # データ変換ルール
  transformations:
    # 列名の変換定義（元のカラム名 → 変換後のカラム名）
    columns_rename:
      所属: 雇用区分コード
      所属名: 雇用区分
      所属コード1: 部門コード
      所属コード1名: 部門
      事業所: 部署コード
      事業所名: 部署
      部門: セグメントコード
      部門名: セグメント
      # 振込金額1: 振込金額

    # 条件付き変換ルール（※変換後のカラム名を使用）
    conditional_rules:
      employment_type:
        # 代表取締役社長
        - conditions:
            部署: 代表取締役社長
          target: 部門コード
          value: 90
        - conditions:
            部署: 代表取締役社長
          target: 部門
          value: 役員
        - conditions:
            部署: 代表取締役社長
          target: 部署コード
          value: 0
        - conditions:
            部署: 代表取締役社長
          target: 雇用区分コード
          value: 0
        - conditions:
            部署: 代表取締役社長
          target: 雇用区分
          value: 役員
        - conditions:
            部署: 代表取締役社長
          target: 部署コード
          value: 0
        - conditions:
            部署: 代表取締役社長
          target: 部署
          value: None                          
        # 取締役
        - conditions:
            部署: 取締役
          target: 部門コード
          value: 90
        - conditions:
            部署: 取締役
          target: 部門
          value: 役員
        - conditions:
            部署: 取締役
          target: 部署コード
          value: 0
        - conditions:
            部署: 取締役
          target: 雇用区分コード
          value: 0
        - conditions:
            部署: 取締役
          target: 雇用区分
          value: 役員
        - conditions:
            部署: 取締役
          target: 部署コード
          value: 0
        - conditions:
            部署: 取締役
          target: 部署
          value: None
        # 監査役
        - conditions:
            部署: 監査役
          target: 部門コード
          value: 90
        - conditions:
            部署: 監査役
          target: 部門
          value: 役員
        - conditions:
            部署: 監査役
          target: 部署コード
          value: 0
        - conditions:
            部署: 監査役
          target: 雇用区分コード
          value: 0
        - conditions:
            部署: 監査役
          target: 雇用区分
          value: 役員
        - conditions:
            部署: 監査役
          target: 部署コード
          value: 0
        - conditions:
            部署: 監査役
          target: 部署
          value: None

      # 部長とITマイスターの所属設定
      department:
        - conditions:
            部署: 部長
          target: 部署
          source: None
        - conditions:
            部署: 部長
          target: 部署コード
          source: None
        - conditions:
            部署: ＩＴマイスター
          target: 部署
          source: None
        - conditions:
            部署: ＩＴマイスター
          target: 部署コード
          source: '0'
        - conditions:
            部門コード: 90
          target: 部門
          source: '共通'

      # セグメントコードの設定
      segment:
        # 基本セグメント設定
        - conditions:
            セグメントコード: 1
          target: セグメントコード
          value: 9001  # 一般
        - conditions:
            セグメントコード: 2
          target: セグメントコード
          value: 2200  # FM
        - conditions:
            セグメントコード: 3
          target: セグメントコード
          value: 3201  # KURUTO（物産）
        - conditions:
            セグメントコード: 4
          target: セグメントコード
          value: 3202  # KURUTO（ｶﾌｪ）
        - conditions:
            セグメントコード: 5
          target: セグメントコード
          value: 1900  # ワクチンCC → 3サービス共通        # セグメントコードの設定
        - conditions:
            セグメントコード: 6
          target: セグメントコード
          value: 3206 # カフェ佐布里
        - conditions:
            セグメントコード: 7
          target: セグメントコード
          value: 3204 # カフェ創造
        - conditions:
            セグメントコード: 8
          target: セグメントコード
          value: 3203 # 創造の杜
        - conditions:
            セグメントコード: 9
          target: セグメントコード
          value: 3205 # 佐布里



        # 部署別セグメント設定
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 31
            セグメントコード: 9001
          target: セグメントコード
          value: 1900  # コンシューマ
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 21
            セグメントコード: 9001
          target: セグメントコード
          value: 1900  # 技術
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 71
            セグメントコード: 9001
          target: セグメントコード
          value: 2300  # 地域サポート
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 18
            セグメントコード: 9001
          target: セグメントコード
          value: 3101  # にぎわい創生課
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 37
            セグメントコード: 9001
          target: セグメントコード
          value: 1409  # ソリューション課
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 63
            セグメントコード: 9001
          target: セグメントコード
          value: 2100  # 編成課
        - conditions:
            雇用区分コード: "> 1"
            部署コード: 64
            セグメントコード: 9001
          target: セグメントコード
          value: 2100  # 制作課

      # セグメント名称の設定
      segment_names:
        - conditions:
            セグメントコード: 9001
          target: セグメント
          value: 全社費
        - conditions:
            セグメントコード: 1900
          target: セグメント
          value: 3ｻｰﾋﾞｽ共通
        - conditions:
            セグメントコード: 2100
          target: セグメント
          value: ｺﾐｭﾆﾃｨCH
        - conditions:
            セグメントコード: 2200
          target: セグメント
          value: ｺﾐｭﾆﾃｨFM
        - conditions:
            セグメントコード: 2300
          target: セグメント
          value: ちたまる
        - conditions:
            セグメントコード: 1409
          target: セグメント
          value: ｿﾘｭｰｼｮﾝ
        - conditions:
            セグメントコード: 3101
          target: セグメント
          value: ｲﾍﾞﾝﾄ

    # コード変換ルール（※変換後のカラム名を使用）
    code_mappings:
      department_code:
        0: '90'   # 共通
        10: '41'  # 経営企画部
        20: '31'  # コンシューマ事業部
        40: '81'  # IT推進部
        50: '21'  # 技術サービス部
        60: '11'  # まちづくり事業部
        70: '61'  # 地域情報部

      # 部署コードの変換
      section_code:
        10: '10'  # 代表取締役社長
        11: None  # 取締役 ＆ 経営企画部部長
        12: '12'  # 監査役
        13: '46'  # 総務人事課
        14: '42'  # 経営戦略課
        23: '37'  # 地域営業課
        24: '58'  # 暮らしサポート課
        25: '33'  # リテンション課
        26: '55'  # カスタマーセンター
        27: '57'  # お客様管理課
        15: '82'  # IT推進課
        51: None  # 技術サービス部長
        53: '22'  # 技術課
        54: '23'  # 通信課
        61: None  # まちづくり事業部長
        63: '18'  # にぎわい創生課
        64: '72'  # 地域サポート課
        65: '38'  # ソリューション課
        66: '71'  # エリアプロモーション課
        71: None  # 地域情報部長
        73: '63'  # 編成課
        74: '64'  # 制作課
        111: None

  # 計算・集計ルール（※変換後のカラム名を使用）
  calculations:
    # 合計列の定義
    total_columns:
      資格手当合計: qualification
      時間外勤務手当合計: overtime
      その他手当合計: allowance
      通勤手当合計: commute
      控除合計: deduction
      支給総額: total_payment
      振込金額: transfer_payment

    # 最終計算項目
    final_columns:
      - 支給総額
      - 控除合計
      - 差引支給額
      - 振込金額


# 賞与データ処理ルール
bonus:
  columns_order:
    - 会社NO
    - 対象年月
    - コード
    - 氏名
    - 原価区分
    - 雇用形態
    - 雇用形態名
    - 部署コード
    - 部署名
    - 所属
    - 所属名

  columns_rename:
    会社ＮＯ: 会社NO
    所属コード: 部門コード
    所属名称: 部門名
    社員コード: コード
    社員氏名: 氏名
    部門コード: 部署コード
    部門名称: 部署コード名

  conditional_rules:
    - condition: "雇用形態 == 1"
      value: "正社員"
      target_column: "雇用形態名"
    - condition: "雇用形態 == 0"
      value: "契約社員"
      target_column: "雇用形態名"
    - condition: "原価区分 == 1"
      value: "原価"
      target_column: "原価区分名"
    - condition: "原価区分 == 2"
      value: "販管費"
      target_column: "原価区分名"

# 処理フロー定義
processing_flow:
  1: input_validation    # 入力データの検証（変換前のカラム名）
  2: numeric_conversion  # 数値変換（変換前のカラム名）
  3: column_renaming    # カラム名の変換
  4: conditional_rules  # 条件付き変換（変換後のカラム名）
  5: code_mapping      # コード変換（変換後のカラム名）
  6: total_calculation # 合計計算（変換後のカラム名）
  7: output_formatting # 出力整形（変換後のカラム名） 