# 共通設定
common:
  encoding: cp932
  date_format: "%Y%m"

# 給与データ処理ルール
salary:
  # 入力データの検証設定（元のカラム名を使用）
  input_validation:
    # 必須列の定義
    required_columns:
      - 会社NO
      - 対象年月
      - コード
      - 氏名
      - 原価区分
      - 所属
      - 所属名
      - 所属コード1
      - 所属コード1名
      - 事業所
      - 事業所名
      - 部門
      - 部門名
      - 基本給
      - 固･職級手当
      - 固･役職手当
      - 残業平日普通
      - 残業平日深夜
      - 60超手当
      - 休日勤務手当
      - 休日深夜手当
      - 遅刻早退控除
      - 欠勤控除
      - 固･家族手当
      - 住宅手当
      - 食事手当
      - 固･調整手当
      - 固･その他
      - 特別勤務手当
      - 在宅勤務手当
      - 呼出勤務手当
      - 褒賞金
      - 公的資格合格金
      - 遡及分
      - 変動その他
      - 固･DC代替措置
      - DC掛金初月
      - 課税通勤
      - 非課税通勤

    # 数値列の定義（元のカラム名を使用）
    numeric_columns:
      # 基本給与
      - 基本給
      # 資格手当
      - 固･職級手当
      - 固･役職手当
      - 資格手当合計
      # 時間外手当
      - 残業平日普通
      - 残業平日深夜
      - 60超手当
      - 休日勤務手当
      - 休日深夜手当
      - 遅刻早退控除
      - 欠勤控除
      - 時間外勤務手当合計
      # その他手当
      - 固･家族手当
      - 住宅手当
      - 食事手当
      - 固･調整手当
      - 固･その他
      - 特別勤務手当
      - 在宅勤務手当
      - 呼出勤務手当
      - 褒賞金
      - 公的資格合格金
      - 遡及分
      - 変動その他
      - 固･DC代替措置
      - DC掛金初月
      - その他手当合計
      # 通勤手当
      - 課税通勤
      - 非課税通勤
      - 通勤手当合計
      # 控除項目
      - P健保介護
      - 厚生年金個人
      - 雇用保険
      - 所得税
      - 住民税
      - 年調過不足
      - 加入者拠出
      - ランチ弁当代
      - ﾜｰｸﾘｨ知多
      - 自動車保険
      - ＣＭ会費
      - ＴＧ特別医療
      - 会社立替精算
      - その他控除
      - 控除合計
      # 最終計算項目
      - 支給総額
      - 総支給額合計
      - 差引支給額
      - 振込金額
  

  # 入力データのグループ定義（元のカラム名を使用）
  input_columns:
    # 基本情報カラム
    basic_info:
      - 会社NO
      - 対象年月
      - コード
      - 氏名
      - 原価区分
      - 所属
      - 所属名
      - 所属コード1
      - 所属コード1名
      - 事業所
      - 事業所名
      - 部門
      - 部門名

    # 給与カラム
    salary_items:
      # 基本給与
      base:
        - 基本給
      # 資格手当
      qualification:
        - 固･職級手当
        - 固･役職手当
      # 時間外手当
      overtime:
        - 残業平日普通
        - 残業平日深夜
        - 60超手当
        - 休日勤務手当
        - 休日深夜手当
        - 遅刻早退控除
        - 欠勤控除
      # その他手当
      allowance:
        - 固･家族手当
        - 住宅手当
        - 食事手当
        - 固･調整手当
        - 固･その他
        - 特別勤務手当
        - 在宅勤務手当
        - 呼出勤務手当
        - 褒賞金
        - 公的資格合格金
        - 遡及分
        - 変動その他
        - 固･DC代替措置
        - DC掛金初月
      # 通勤手当
      commute:
        - 課税通勤
        - 非課税通勤
      # 控除項目
      deduction:
        - P健保介護
        - 厚生年金個人
        - 雇用保険
        - 所得税
        - 住民税
        - 年調過不足
        - 加入者拠出
        - ランチ弁当代
        - ﾜｰｸﾘｨ知多
        - 自動車保険
        - ＣＭ会費
        - ＴＧ特別医療
        - 会社立替精算
        - その他控除

  # データ変換ルール
  transformations:
    # 列名の変換定義（元のカラム名 → 変換後のカラム名）
    columns_rename:
      所属: 雇用形態
      所属名: 雇用形態名
      所属コード1: 部署コード
      所属コード1名: 部署コード名
      事業所: 所属
      事業所名: 所属名
      部門: ｾｸﾞﾒﾝﾄ
      部門名: ｾｸﾞﾒﾝﾄ名
      振込金額1: 振込金額


  # 集計定義（変換後のカラム名を使用）
  aggregations:
    # 合計列の定義
    total_columns:
      資格手当合計: qualification
      時間外勤務手当合計: overtime
      その他手当合計: allowance
      通勤手当合計: commute
      控除合計: deduction
      支給総額: total_payment

    # 最終計算項目の定義
    final_columns:
      - 支給総額
      - 控除合計
      - 差引支給額
      - 振込金額

  # 出力設定（変換後のカラム名を使用）
  output_settings:
    # 出力カラム順序
    columns_order:
      - 会社NO
      - 対象年月
      - コード
      - 氏名
      - 原価区分
      - 雇用形態
      - 雇用形態名
      - 部署コード
      - 部署コード名
      - 所属
      - 所属名
      - ｾｸﾞﾒﾝﾄ
      - ｾｸﾞﾒﾝﾄ名
      - 基本給
      - 資格手当合計
      - 時間外勤務手当合計
      - その他手当合計
      - 通勤手当合計
      - 支給総額
      - 控除合計
      - 差引支給額
      - 振込金額

# 賞与データ処理ルール
bonus:
  columns_order:
    - 会社NO
    - 対象年月
    - コード
    - 氏名
    - 原価区分
    - 雇用形態
    - 雇用形態名
    - 部署コード
    - 部署コード名
    - 所属
    - 所属名

  columns_rename:
    会社ＮＯ: 会社NO
    所属コード: 所属
    所属名称: 所属名
    社員コード: コード
    社員氏名: 氏名
    部門コード: 部署コード
    部門名称: 部署コード名

  conditional_rules:
    - condition: "雇用形態 == 1"
      value: "正社員"
      target_column: "雇用形態名"
    - condition: "雇用形態 == 0"
      value: "契約社員"
      target_column: "雇用形態名"
    - condition: "原価区分 == 1"
      value: "原価"
      target_column: "原価区分名"
    - condition: "原価区分 == 2"
      value: "販管費"
      target_column: "原価区分名" 